# Generated by Django 3.0.1 on 2019-12-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ActionsUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('actionsCalendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo_sportingCristal.ActionsCalendar')),
                ('actionsUrl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo_sportingCristal.ActionsUrl')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='modelo_sportingCristal.Team')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo_sportingCristal.Championship')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='modelo_sportingCristal.Team')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo_sportingCristal.Meta')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo_sportingCristal.Referee')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo_sportingCristal.Stadium')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo_sportingCristal.State')),
            ],
        ),
    ]
