# Generated by Django 3.0.1 on 2019-12-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_sportingCristal', '0002_auto_20191227_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionscalendar',
            name='icon',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='actionscalendar',
            name='url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='actionsurl',
            name='icon',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='actionsurl',
            name='url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='championship',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='away_goals',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='away_penalty_goals',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='dateTime',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_confirmed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='local_goals',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='local_penalty_goals',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='on_live',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='period',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='scorer',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='selected',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='ticketing',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='timeStamp',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='is_own_match',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='own_side',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='shortName',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
