# Generated by Django 3.0.1 on 2019-12-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_sportingCristal', '0003_auto_20191227_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_penalty_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='local_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='local_penalty_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ticketing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='timeStamp',
            field=models.IntegerField(null=True),
        ),
    ]
