# Generated by Django 3.0.1 on 2019-12-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_sportingCristal', '0005_auto_20191227_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
